// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaQ10VtjIbV9C7J5P9RJNjCzwjeB3NqP8',
    appId: '1:734289211847:web:2348585c31b1cfd8e969e2',
    messagingSenderId: '734289211847',
    projectId: 'flutter-firebase-messagi-9565f',
    authDomain: 'flutter-firebase-messagi-9565f.firebaseapp.com',
    storageBucket: 'flutter-firebase-messagi-9565f.appspot.com',
    measurementId: 'G-729PF8S4SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVy_wGSoBmCMuKvsODl05_PKn1_sYLTFU',
    appId: '1:734289211847:android:38504a6301bddd22e969e2',
    messagingSenderId: '734289211847',
    projectId: 'flutter-firebase-messagi-9565f',
    storageBucket: 'flutter-firebase-messagi-9565f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw3FKPs1XAkTtH7nDU4AZgbHphV3f80Tg',
    appId: '1:734289211847:ios:2391a04301bda964e969e2',
    messagingSenderId: '734289211847',
    projectId: 'flutter-firebase-messagi-9565f',
    storageBucket: 'flutter-firebase-messagi-9565f.appspot.com',
    iosClientId: '734289211847-jmpe108vi92n4vtjkmhrluctnd5uohm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseMessaging',
  );
}
